### ISSUE TITLE
Function `str-replace` throws Stack Overflow error when trying to replace 190 entries or more

### ISSUE THREAD

**Issue by vasartam** [vasartam/sass-tools#5]
The error is triggered when you try to run this test suite:

```scss
@include true.it('Can replace up to 100 entries') {
	$string: "abc";

	@for $i from 0 to 190 {
		$string: $string + "DUMMY";
	}

	$string: $string + "abc";

	@include true.assert-equal(
			str-replace($string, "DUMMY"),
			"abcabc",
	)
}
```

Notice the changed number of iterations to reproduce the error.

Terminal output:

```
$ npm test

> @vasart/sass-tools@0.2.1 test
> jest

 FAIL  test/sass.test.js
  ● Test suite failed to run

    Stack Overflow

      at FunctionExpression0.accept$1$1 (node_modules/sass/sass.dart.js:83681:22)
      at FunctionExpression0.accept$1 (node_modules/sass/sass.dart.js:83684:19)
      at _EvaluateVisitor_visitBinaryOperationExpression_closure1.call$0 (node_modules/sass/sass.dart.js:81770:39)
      at _EvaluateVisitor1._evaluate0$_addExceptionSpan$1$2 (node_modules/sass/sass.dart.js:80650:23)
      at _EvaluateVisitor1._evaluate0$_addExceptionSpan$2 (node_modules/sass/sass.dart.js:80671:19)
      at _EvaluateVisitor1.visitBinaryOperationExpression$1 (node_modules/sass/sass.dart.js:79858:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.456 s, estimated 1 s
Ran all test suites.
```

The same error is addressed in [the comment](https://css-tricks.com/snippets/sass/str-replace-function/#comment-1763163) under the [original post](https://css-tricks.com/snippets/sass/str-replace-function/) from which the function code was initially copied. It also specifies a rewritten version of the function:

```scss
@function str-replace($string, $search, $replace: '') {

  $index: str-index($string, $search);

  @if $index{

    $searchString: $string;
    $newString: "";
    $end: "";

    @while $index {
      $start: str-slice($searchString, 1, $index - 1);
      $end: str-slice($searchString, $index + str-length($search));
      $searchString: $end;
      $index: str-index($searchString, $search);
      $newString: $newString + $start + $replace;
    }
    @return $newString + $end;
  }
  @return $string;
}
```

Need to test the code above and possibly use it or rewrite the function such as the recursion is removed.
