### ISSUE TITLE
Support for `sass-mq` breakpoints names inside `adaptivity`

### ISSUE THREAD

**Issue by vasartam** [vasartam/sass-tools#8]
When working with site's adaptivity, the library such as [sass-mq](https://github.com/sass-mq/sass-mq) helps a lot. It turns the usual `@media` syntax into a much more readable format:
```scss
.foo {
  @include mq($from: mobile, $until: tablet) {
    background: red;
  }
}
```
It also eliminates the need to keep in mind the exact values of your breakpoints.

However, when using `adaptivity` mixin side-by-side with `mq`, it becomes somewhat confusing. More confusing than if we would have simple `@media` rules instead of `mq` inclusion, possibly:

```scss
.foo {
  @include mq($from: mobile, $until: desktop) {
    background: red;
  }

  @include linear-interpolation(1440px 375px, (
    font-size: 32px 24px,
    line-height: 52px 34px
  ));
}
```

Need to teach the `adaptivity` mixin to accept the following format inside `$screen-widths-list` parameter:

```scss
.foo {
  @include mq($from: mobile, $until: desktop) {
    background: red;
  }

  @include linear-interpolation(desktop mobile, (
    font-size: 32px 24px,
    line-height: 52px 34px
  ));
}
```

I know you can use variables for that, but it would be much more nice to have such a deep integration.
